# Generated by Django 3.1.7 on 2021-03-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablogpage', '0002_auto_20210316_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
